package com.ossanasur.cbconnect.common.enums;
public enum NatureCourrier {
    TRANSMISSION_EXPERTISE, DEMANDE_OFFRE, DEMANDE_PIECES, TRANSMISSION_PV,
    COMPTE_RENDU_AUDIENCE, RELANCE, CONFIRMATION_GARANTIE,
    OFFRE_INDEMNISATION, ACCORD_VICTIME, BAP, AUTRE, OFFRE
}
