package com.ossanasur.cbconnect.common.enums;

public enum StatutSinistre {
    NOUVEAU,
    VALIDE,
    GARANTIE_CONFIRMEE,
    GARANTIE_NON_ACQUISE,
    ATTENTE_PV,
    ATTENTE_RC,
    ATTENTE_PIECES_DE_RECLAMATION,
    MUR,
    OFFRE_EFFECTUE,
    ATTENTE_OFFRE,
    OFFRE_RECUE,
    ACCORD,
    REJET,
    BAP,
    ATTENTE_CHEQUE,
    CHEQUE_RECU,
    PARTIELLEMENT_PAYE,
    SOLDE,
    CLOTURE,
    REOUVERT,
    CONTENTIEUX,
    ARBITRAGE,
    SANS_SUITE
}
