package com.ossanasur.cbconnect.common.enums;

public enum TypeTable {
    ORGANISME, PROFIL, UTILISATEUR, HABILITATION, PARAMETRE, MODULE_ENTITY,
    PAYS, ENTITE_CONSTAT,
    SINISTRE, ASSURE, VICTIME,
    PV_SINISTRE,
    EXPERT, EXPERTISE_MEDICALE, EXPERTISE_MATERIELLE,
    DOSSIER_RECLAMATION, FACTURE_RECLAMATION,
    OFFRE_INDEMNISATION, AYANT_DROIT,
    ENCAISSEMENT, PAIEMENT, PREFINANCEMENT,
    LOT_APPROVISIONNEMENT, COMMANDE_ATTESTATION, TRANCHE_LIVRAISON_ATTESTATION,
    FACTURE_ATTESTATION, CHEQUE_RECU_ATTESTATION,
    OSSAN_GED_DOSSIER, OSSAN_GED_DOCUMENT,
    COURRIER, RENCONTRE_BILATERALE, DOSSIER_BILATERALE,
    DOMAINE_MAIL_CONFIG, CONFIGURATION_MAIL_UTILISATEUR,
    SIGNATURE_MAIL, TEMPLATE_MAIL, MAIL_ENVOYE, MAIL_RECU,
    ECRITURE_COMPTABLE, PLAN_COMPTABLE,
    NOTIFICATION_DELAI, PENALITE_CALCULEE
}
