package com.ossanasur.cbconnect.common.enums;
public enum TypeDocumentOssanGed {
    EXPERTISE_MED, EXPERTISE_AUTO, CMI, CMC, PV, FACTURE_MED, FACTURE_RECLAMATION,
    ORDONNANCE, FRAIS_FUNERAIRES, ACTE_DECES, ACTE_MARIAGE, ACTE_NAISSANCE,
    CNI, CERTIFICAT_VIE, SCOLARITE, COURRIER, OFFRE, ACCORD, FACTURE_ATTESTATION, AUTRES
}
