package com.ossanasur.cbconnect.common.enums;
public enum TypeTemplateMailEnum {
    DEMANDE_OFFRE, TRANSMISSION_EXPERTISE, DEMANDE_PIECES, RELANCE,
    CONFIRMATION_GARANTIE, TRANSMISSION_PV, ACCORD_VICTIME, BAP,
    COMPTE_RENDU_AUDIENCE, PROFORMA_ATTESTATION, LIBRE
}
